services:
  nmos-crosspoint:
    build:
      context: ./
    image: gemini2350/nmos-crosspoint_v3:latest

    container_name: nmos-crosspoint_v3
    hostname: nmos-crosspoint_v3
    domainname: local

    network_mode: host

    volumes:
      - ./server/config:/nmos-crosspoint/server/config
      - ./server/state:/nmos-crosspoint/server/state

    restart: unless-stopped